import express, { Express, Request, Response } from "express";
import userRoutes from "./routes/users";
import clientRoutes from "./routes/clients";
import authRoutes from "./routes/auth";
import uploadClients from "./routes/upload/clients";
import campaignRoutes from "./routes/campaign";
import uploadCampaigns from "./routes/upload/campaign";
import generalRoutes from "./routes/generals";
import uploadGenerals from "./routes/upload/generals";
import uploadDecils from "./routes/upload/decils";
import decilRoutes from "./routes/decils";
import uploadBalances from "./routes/upload/balances";
import balanceRoutes from "./routes/balances";
import emailRoutes from "./routes/emails";
import uploadEmails from "./routes/upload/emails";
import phoneRoutes from "./routes/phones";
import uploadPhones from "./routes/upload/phones";
import uploadBases from "./routes/upload/bases";
import baseRoutes from "./routes/bases";
import uploadAssignments from "./routes/upload/assignment";
import uploadWallets from "./routes/upload/wallet";
import uploadPayments from "./routes/upload/payment";
import uploadManagements from "./routes/upload/management";
import uploadEps from "./routes/upload/eps";
import uploadProperties from "./routes/upload/properties";
import uploadEmployments from "./routes/upload/employment";
import assignmentRoutes from "./routes/assignment";
import walletRoutes from "./routes/wallet";
import paymentRoutes from "./routes/payment";
import managementRoutes from "./routes/management";
import epsRoutes from "./routes/eps";
import propertyRoutes from "./routes/properties";
import employmentRoutes from "./routes/employment";

const app: Express = express();
const port = process.env.PORT || 3000;

app.use(express.json());
app.use("/api", userRoutes);
app.use("/api", clientRoutes);
app.use("/api", campaignRoutes);
app.use("/api", generalRoutes);
app.use("/api", decilRoutes);
app.use("/api", balanceRoutes);
app.use("/api", emailRoutes);
app.use("/api", phoneRoutes);
app.use("/api", baseRoutes);
app.use("/api", authRoutes);
app.use("/api", uploadClients);
app.use("/api", uploadCampaigns);
app.use("/api", uploadGenerals);
app.use("/api", uploadDecils);
app.use("/api", uploadBalances);
app.use("/api", uploadEmails);
app.use("/api", uploadPhones);
app.use("/api", uploadBases);
app.use("/api", uploadAssignments);
app.use("/api", uploadWallets);
app.use("/api", uploadPayments);
app.use("/api", uploadManagements);
app.use("/api", uploadEps);
app.use("/api", uploadProperties);
app.use("/api", uploadEmployments);
app.use("/api", assignmentRoutes);
app.use("/api", walletRoutes);
app.use("/api", paymentRoutes);
app.use("/api", managementRoutes);
app.use("/api", epsRoutes);
app.use("/api", propertyRoutes);
app.use("/api", employmentRoutes);

app.get("/", (req: Request, res: Response) => {
	res.send("¡Bienvenido a la API zolug!");
});

app.listen(port, () => {
	console.log(`⚡️[servidor]: Servidor corriendo en http://localhost:${port}`);
});
